### ISSUE TITLE
Unable to uninstall 

### ISSUE THREAD

**Issue by simonprice33** [DevExpress/AjaxControlToolkit#176]
I am trying to uninstall the tool kit as I have had a problem with my machine and I am getting this error information and need a way to resolve it 

VSIX Installer error code: 3001 (Unknown VSIXInstaller exception)

2016-07-20 12:26:40 | INFO  | App.Application_Startup                  | Installer started 
2016-07-20 12:26:40 | INFO  |                                              VSIX name: ASP.NET AJAX Control Toolkit 
2016-07-20 12:26:40 | INFO  |                                              VSIX id: e79bade7-6755-466f-9788-3d8243bdcc5f 
2016-07-20 12:26:40 | INFO  |                                              VSIX version: 16.1.0.0 
2016-07-20 12:26:40 | INFO  | App.Application_Startup                  | Process Info 
2016-07-20 12:26:40 | INFO  |                                              OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
2016-07-20 12:26:40 | INFO  |                                              Is 64bit: True 
2016-07-20 12:26:40 | INFO  |                                              Is admin: False 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2010 not detected 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2012 professional detected 
2016-07-20 12:26:41 | INFO  | VsUtility.GetPendingDeletions            | Pending deletions list for 2012 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.GetInstallDirFromHklm    | InstallDir for 2012: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\ 
2016-07-20 12:26:41 | TRACE | EnvironmentInfo.GetInstallerPath         | C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\VSIXInstaller.exe EXISTS 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2013 not detected 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2015 not detected 
2016-07-20 12:26:41 | INFO  | EnvironmentInfo.GetEnvironmentInfo       | Vsix installer path is C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\VSIXInstaller.exe 
2016-07-20 12:26:41 | INFO  | MainWindow..ctor                         | Installed VS 
2016-07-20 12:26:41 | INFO  |                                              2012, ACT version: 16.1.0.0 C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\gnwmm04b.1a1 
2016-07-20 12:26:41 | INFO  | Installer..ctor                          | User documents ACT directory \\sanuk.santanderuk.corp\andfs\homedirs\13\C0242453\Home\ASP.NET AJAX Control Toolkit 
2016-07-20 12:26:41 | TRACE | PageInstall..ctor                        | Initializing buttons 
2016-07-20 12:26:41 | INFO  | PageInstall.InitButtons                  | Buttons initialization info 
2016-07-20 12:26:41 | INFO  |                                              ACT extension is not installed in any supported Vs: False 
2016-07-20 12:26:41 | INFO  |                                              ACT extension is installed in all supported VSs: True 
2016-07-20 12:26:41 | INFO  |                                              ACT extension updated is required: False 
2016-07-20 12:26:41 | TRACE | PageInstall..ctor                        | Install page initialized 
2016-07-20 12:26:45 | TRACE | MainWindow.ShowUninstallProgressPage     | Progress page is shown 
2016-07-20 12:26:45 | INFO  | VsUtility.GetPendingDeletions            | Pending deletions list for 2012 
2016-07-20 12:26:45 | INFO  | VsixInstallerWrapper.Run                 | Run VSIXInstaller with arguments: '/quiet /uninstall:e79bade7-6755-466f-9788-3d8243bdcc5f' 
2016-07-20 12:27:07 | INFO  | VsixInstallerWrapper.Run                 | VSIXInstaller exit code: 3001 
2016-07-20 12:27:07 | INFO  | Installer.Uninstall                      | VSIXInstaller log:

20/07/2016 12:26:46 - Microsoft VSIX Installer
20/07/2016 12:26:46 - -------------------------------------------
20/07/2016 12:26:46 - Initializing Uninstall...
20/07/2016 12:27:07 - System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Settings.RegistryWritableSettingsStore.CreateCollection(String collectionPath)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UpdateLastExtensionsChange()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeExtensionsStartupFingerprint(IEnumerable`1 enabledExtensions, Boolean safeMode)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService..ctor(SettingsManager settings, CultureInfo preferredCulture, ExtensionManagerServiceMode mode, IEnumerable`1 enabledExtensions)
   at VSIXInstaller.SupportedVSSKU.InitializeExtensionManager()
   at VSIXInstaller.App.GetExtensionManager(SupportedVSSKU sku)
   at VSIXInstaller.App.InitializeUninstall()
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
 
2016-07-20 12:27:07 | TRACE | Installer.TryRemoveDirectory             | Removing directory: C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\ASP.NET AJAX Control Toolkit 
2016-07-20 12:27:07 | WARN  | Installer.TryRemoveDirectory             | C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\ASP.NET AJAX Control Toolkit{0} not found

**Comment by simonprice33** [comment]
I have also run the installation media as admin as below and still the same issue 

VSIX Installer error code: 3001 (Unknown VSIXInstaller exception)

2016-07-20 12:29:28 | INFO  | App.Application_Startup                  | Installer started 
2016-07-20 12:29:28 | INFO  |                                              VSIX name: ASP.NET AJAX Control Toolkit 
2016-07-20 12:29:28 | INFO  |                                              VSIX id: e79bade7-6755-466f-9788-3d8243bdcc5f 
2016-07-20 12:29:28 | INFO  |                                              VSIX version: 16.1.0.0 
2016-07-20 12:29:28 | INFO  | App.Application_Startup                  | Process Info 
2016-07-20 12:29:28 | INFO  |                                              OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
2016-07-20 12:29:28 | INFO  |                                              Is 64bit: True 
2016-07-20 12:29:28 | INFO  |                                              Is admin: True 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2010 not detected 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2012 professional detected 
2016-07-20 12:29:29 | INFO  | VsUtility.GetPendingDeletions            | Pending deletions list for 2012 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.GetInstallDirFromHklm    | InstallDir for 2012: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\ 
2016-07-20 12:29:29 | TRACE | EnvironmentInfo.GetInstallerPath         | C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\VSIXInstaller.exe EXISTS 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2013 not detected 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.VsIsInstalled            | VisualStudio 2015 not detected 
2016-07-20 12:29:29 | INFO  | EnvironmentInfo.GetEnvironmentInfo       | Vsix installer path is C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\VSIXInstaller.exe 
2016-07-20 12:29:29 | INFO  | MainWindow..ctor                         | Installed VS 
2016-07-20 12:29:29 | INFO  |                                              2012, ACT version: 16.1.0.0 C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\gnwmm04b.1a1 
2016-07-20 12:29:29 | INFO  | Installer..ctor                          | User documents ACT directory \\sanuk.santanderuk.corp\andfs\homedirs\13\C0242453\Home\ASP.NET AJAX Control Toolkit 
2016-07-20 12:29:29 | TRACE | PageInstall..ctor                        | Initializing buttons 
2016-07-20 12:29:29 | INFO  | PageInstall.InitButtons                  | Buttons initialization info 
2016-07-20 12:29:29 | INFO  |                                              ACT extension is not installed in any supported Vs: False 
2016-07-20 12:29:29 | INFO  |                                              ACT extension is installed in all supported VSs: True 
2016-07-20 12:29:29 | INFO  |                                              ACT extension updated is required: False 
2016-07-20 12:29:29 | TRACE | PageInstall..ctor                        | Install page initialized 
2016-07-20 12:29:31 | TRACE | MainWindow.ShowBlockersPage              | Blockers page is shown 
2016-07-20 12:29:38 | TRACE | MainWindow.ShowUninstallProgressPage     | Progress page is shown 
2016-07-20 12:29:38 | INFO  | VsUtility.GetPendingDeletions            | Pending deletions list for 2012 
2016-07-20 12:29:38 | INFO  | VsixInstallerWrapper.Run                 | Run VSIXInstaller with arguments: '/quiet /uninstall:e79bade7-6755-466f-9788-3d8243bdcc5f' 
2016-07-20 12:29:58 | INFO  | VsixInstallerWrapper.Run                 | VSIXInstaller exit code: 3001 
2016-07-20 12:29:58 | INFO  | Installer.Uninstall                      | VSIXInstaller log:

20/07/2016 12:29:39 - Microsoft VSIX Installer
20/07/2016 12:29:39 - -------------------------------------------
20/07/2016 12:29:39 - Initializing Uninstall...
20/07/2016 12:29:58 - System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Settings.RegistryWritableSettingsStore.CreateCollection(String collectionPath)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.UpdateLastExtensionsChange()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InitializeExtensionsStartupFingerprint(IEnumerable`1 enabledExtensions, Boolean safeMode)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService..ctor(SettingsManager settings, CultureInfo preferredCulture, ExtensionManagerServiceMode mode, IEnumerable`1 enabledExtensions)
   at VSIXInstaller.SupportedVSSKU.InitializeExtensionManager()
   at VSIXInstaller.App.GetExtensionManager(SupportedVSSKU sku)
   at VSIXInstaller.App.InitializeUninstall()
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
 
2016-07-20 12:29:58 | TRACE | Installer.TryRemoveDirectory             | Removing directory: C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\ASP.NET AJAX Control Toolkit 
2016-07-20 12:29:58 | WARN  | Installer.TryRemoveDirectory             | C:\Users\c0242453\AppData\Local\Microsoft\VisualStudio\11.0\Extensions\ASP.NET AJAX Control Toolkit{0} not found

**Comment by MikhailTymchukDX** [comment]
Hi @simonprice33 ,
This exception shows that something is wrong with your registry, and VSIX installer cannot uninstall the extension. We need more info to understand what can go wrong.

Please provide the following information:
* A list of folders in `%LOCALAPPDATA%\Microsoft\VisualStudio\11.0\Extensions`
* The exported registry branch `HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\11.0\ExtensionManager` (see the screenshot)
![image](https://cloud.githubusercontent.com/assets/17080984/16987620/d7c11a26-4e95-11e6-8f0c-b956cd727278.png)
