### ISSUE TITLE
Json parse errors from TabContainer.LoadClientState

### ISSUE THREAD

**Issue by kitching** [DevExpress/AjaxControlToolkit#330]
We make extensive use of the TabContainer in our web forms project. For a long time the logs have been filled with many instances of the following exception which has lately only occurred with browsers: 
chrome 47/48/54/55/57 & firefox 43/44, never IE. It seems others have experienced the same, eg http://forum.kartris.com/Topic3405.aspx.  We've seen this in all recent versions, including 16 and 17.1.

We've found it tough to reproduce but based on the error message we think:
1) The problem is in TabContainer.LoadClientState
2)  &*quot; may appear in the json string parameter where " is expected.

NOTE: Take out all instances of * in this post which we've added just to prevent html conversion.

We added a string replace in the method which seems to have resolved it.

CODE:

protected override void LoadClientState(string clientState)
{
	clientState = clientState.Replace("&*quot;", """);  // FIX?
	var state = (Dictionary<string, object>)new JavaScriptSerializer().DeserializeObject(clientState);

EXCEPTION:

Exception : System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.ArgumentException: Invalid object passed in, ':' or '}' expected. (2): {&*quot;ActiveTabIndex&*quot;:0,&*quot;TabEnabledState&*quot;:[true,false,false,false,false,false],&*quot;TabWasLoadedOnceState&*quot;:[false,false,false,false,false,false]}
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeDictionary(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at AjaxControlToolkit.TabContainer.LoadClientState(String clientState)
   at AjaxControlToolkit.ScriptControlBase.LoadPostData(String postDataKey, NameValueCollection postCollection)
   at AjaxControlToolkit.TabContainer.LoadPostData(String postDataKey, NameValueCollection postCollection)
   at System.Web.UI.Page.ProcessPostData(NameValueCollection postData, Boolean fBeforeLoad)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by MikhailTymchukDX** [comment]
Hi @kitching 

I checked client state deserialization in Chrome 57 and Firefox 43 and could not reproduce this issue.
I think it is caused by some external factors and more info is needed to provide a proper fix.

For now, I suggest you to derive a new class from `TabContainer` and place your fix there:
```cs
public class MyTabContainer : TabContainer {
    protected override void LoadClientState(string clientState) {
        clientState = clientState.Replace("&*quot;", "\"");
        base.LoadClientState(clientState);
    }
}
```

Don't forget to register it:
```aspx
<%@ Register Assembly="Tabs" TagPrefix="my" Namespace="Tabs" %>
```

Then use it instead of `ajaxToolkit:TabContainer`:
```aspx
<my:MyTabContainer runat="server">
	<ajaxToolkit:TabPanel runat="server">
		...
	</ajaxToolkit:TabPanel>
	...
</my:MyTabContainer>
```
