### ISSUE TITLE
Error when installing the toolkit v17.1.1 to Visual Studio 2013

### ISSUE THREAD

**Issue by blakazulu** [DevExpress/AjaxControlToolkit#369]
### The installation method
- [x] Installer
- [x] NuGet package
- [ ] A custom build from the source code

### Actual result
VSIX Installer error code: 2003 (VSIXInstaller.NoApplicableSKUsException)

2017-07-15 11:42:43 | INFO  | App.Application_Startup                  | Installer started 
2017-07-15 11:42:43 | INFO  |                                              VSIX name: ASP.NET AJAX Control Toolkit 
2017-07-15 11:42:43 | INFO  |                                              VSIX id: e79bade7-6755-466f-9788-3d8243bdcc5f 
2017-07-15 11:42:43 | INFO  |                                              VSIX version: 17.1.1.0 
2017-07-15 11:42:43 | INFO  | App.Application_Startup                  | Process Info 
2017-07-15 11:42:43 | INFO  |                                              OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
2017-07-15 11:42:43 | INFO  |                                              Is 64bit: True 
2017-07-15 11:42:43 | INFO  |                                              Is admin: False 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2010 not detected 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2012 not detected 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2013 professional detected 
2017-07-15 11:42:43 | ERROR | Error while querying VS2017 instances:

Unable to load DLL 'Microsoft.VisualStudio.Setup.Configuration.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.GetInstallDirFromHklm    | InstallDir for 2013: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ 
2017-07-15 11:42:43 | TRACE | EnvironmentInfo.GetInstallerPath         | C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\VSIXInstaller.exe EXISTS 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.CheckLegacyVersionIsInstalled | VisualStudio 2015 not detected 
2017-07-15 11:42:43 | ERROR | Error while querying VS2017 instances:

Unable to load DLL 'Microsoft.VisualStudio.Setup.Configuration.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.GetInstalledInstances    | VisualStudio 2017 not detected 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.GetEnvironmentInfo       | C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\VSIXInstaller.exe 
2017-07-15 11:42:43 | INFO  | EnvironmentInfo.GetEnvironmentInfo       | Vsix installer path is C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\VSIXInstaller.exe 
2017-07-15 11:42:43 | INFO  | MainWindow..ctor                         | Installed VS 
2017-07-15 11:42:43 | INFO  |                                              2013, ACT version: none  
2017-07-15 11:42:43 | INFO  | Installer..ctor                          | User documents ACT directory \\Mac\Home\Documents\ASP.NET AJAX Control Toolkit 
2017-07-15 11:42:43 | TRACE | PageInstall..ctor                        | Initializing buttons 
2017-07-15 11:42:43 | INFO  | PageInstall.InitButtons                  | Buttons initialization info 
2017-07-15 11:42:43 | INFO  |                                              ACT extension is not installed in any supported Vs: True 
2017-07-15 11:42:43 | INFO  |                                              ACT extension is installed in all supported VSs: False 
2017-07-15 11:42:43 | INFO  |                                              ACT extension update is required: False 
2017-07-15 11:42:43 | TRACE | PageInstall..ctor                        | Install page initialized 
2017-07-15 11:42:44 | TRACE | MainWindow.ShowEulaPage                  | EULA page is shown 
2017-07-15 11:42:48 | TRACE | MainWindow.ShowInstallProgressPage       | Progress page is shown 
2017-07-15 11:42:48 | INFO  | VsixInstallerWrapper.Run                 | Run VSIXInstaller with arguments: '/quiet "C:\Users\shakazulu\AppData\Local\Temp\ACTInstaller_72edcfaa-a705-48b2-9bda-ad7c977a028a\Extension.vsix"' 
2017-07-15 11:42:49 | INFO  | VsixInstallerWrapper.Run                 | VSIXInstaller exit code: 2003 
2017-07-15 11:42:49 | INFO  | Installer.InstallExtension               | VSIXInstaller log:

7/15/17 11:42:48 PM - Microsoft VSIX Installer
7/15/17 11:42:48 PM - -------------------------------------------
7/15/17 11:42:48 PM - Initializing Install...
7/15/17 11:42:48 PM - Extension Details...
7/15/17 11:42:48 PM - 	Identifier      : e79bade7-6755-466f-9788-3d8243bdcc5f
7/15/17 11:42:48 PM - 	Name            : ASP.NET AJAX Control Toolkit
7/15/17 11:42:48 PM - 	Author          : CodePlex Foundation
7/15/17 11:42:48 PM - 	Version         : 17.1.1.0
7/15/17 11:42:48 PM - 	Description     : ASP.NET AJAX Control Toolkit Visual Studio integration package
7/15/17 11:42:48 PM - 	Locale          : en-US
7/15/17 11:42:48 PM - 	MoreInfoURL     : 
7/15/17 11:42:48 PM - 	InstalledByMSI  : False
7/15/17 11:42:48 PM - 	SupportedFrameworkVersionRange : [4.0,4.6]
7/15/17 11:42:48 PM - 
7/15/17 11:42:48 PM - 	Supported Products : 
7/15/17 11:42:48 PM - 		Microsoft.VisualStudio.Community
7/15/17 11:42:48 PM - 			Version : [10.0,15.0]
7/15/17 11:42:48 PM - 
7/15/17 11:42:48 PM - 	References      : 
7/15/17 11:42:48 PM - 
7/15/17 11:42:48 PM - Searching for applicable products...
7/15/17 11:42:49 PM - Found installed product - Microsoft Visual Studio Professional 2013
7/15/17 11:42:49 PM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
7/15/17 11:42:49 PM - Found installed product - Global Location
7/15/17 11:42:49 PM - Found installed product - ssms
7/15/17 11:42:49 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
 
2017-07-15 11:42:49 | TRACE | Installer.TryRemoveDirectory             | Removing directory: C:\Users\shakazulu\AppData\Local\Temp\ACTInstaller_72edcfaa-a705-48b2-9bda-ad7c977a028a 

### Expected result
when I tried to install it from the installation this is the error that i received. i have windows 7 and visual studio 2013 professional.

### NuGet package
when I tried to install with NuGet package it was ok but i didn't see any tools in the toolkit.

**Comment by MikhailTymchukDX** [comment]
It seems that the installer tries to apply the wrong VSIX.
Please try to install this VSIX package, which is used in our installer internally while we are investigating what causes this issue: [AjaxControlToolkit.17.1.1.0.zip](https://github.com/DevExpress/AjaxControlToolkit/files/1152065/AjaxControlToolkit.17.1.1.0.zip)

**Comment by blakazulu** [comment]
thank you for the quick response and quick fix.
waiting to see what happened to the installer, this problem happened to a lot of people that i know.

**Comment by MikhailTymchukDX** [comment]
Hi @blakazulu 
We updated our installer logic, so you can download the fixed version from [the releases](https://github.com/DevExpress/AjaxControlToolkit/releases/download/17.1.1/AjaxControlToolkit.Installer.17.1.1.exe) or from [our site](https://go.devexpress.com/AjaxControlToolkit_Website_Download.aspx).

Feel free to comment on this issue if you are still having problems with the installation.
