### ISSUE TITLE
AjaxControlToolkit working on one server but not another.

### ISSUE THREAD

**Issue by araczynski** [DevExpress/AjaxControlToolkit#485]
Not sure what's going on here... publishing an app to one server and everything works fine, publishing it to another and the Ajax components (modalpopup extender/etc) don't work/fire on the other.  For example the popup is always visible, and textbox doesn't respond with the datepicker extender.  The ajaxcontroltoolkit.dll is in the /bin of both apps.  Application pool is the same, file permissions seem to be the same.

This doesn't seem to be app specific, as a different app published to both servers behaves the same (i.e. works on the one, and not the other).  The apps load and don't complain about anything, just the Ajax stuff is ignored on one.  Both are running version 18.1.1 targeting .NET4.  IIS8.5 on Windows Server 2012R2.

FWIW, the unhappy server is also running Joomla/PHP, just in case....

Event logger on the unhappy one gives me the below, which doesn't lead me to much:

Event code: 3012 
Event message: An error occurred processing a web or script resource request. The requested resource 's|WebForms.js' does not exist or there was a problem loading it. 
Event time: 5/22/2019 12:22:17 PM 
Event time (UTC): 5/22/2019 5:22:17 PM 
Event ID: 1547dec8b40d481eb8d923e7cd23d04d 
Event sequence: 14 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1/ROOT/ECReferral-13-132030180589094021 
    Trust level: Full 
    Application Virtual Path: /ECReferral 
    Application Path: C:\inetpub\net\ECReferral\ 
    Machine name: WEB 
 
Process information: 
    Process ID: 7484 
    Process name: w3wp.exe 
    Account name: GHAEA\ghadmin 
 
Exception information: 
    Exception type: HttpException 
    Exception message: Server cannot set content type after HTTP headers have been sent.
   at System.Web.HttpResponse.set_ContentType(String value)
   at System.Web.Handlers.AssemblyResourceLoader.System.Web.IHttpHandler.ProcessRequest(HttpContext context)

 
 
Request information: 
    Request URL: https://www.xxxxxxxxxxxxx.org:443/ECReferral/WebResource.axd?d=BpsrWo4df7eJtElRJXKfi_rwxWYQyV0lsiE572lC-sGGDgFiIaBvyczFc3Kk7-5ZmnoKQk2c-MEC4Gli0Irw7T2pootoaC9BUm9m4mplYGU1&t=636765284300000000 
    Request path: /ECReferral/WebResource.axd 
    User host address: xxxxxxxxxxx 
    User: andy 
    Is authenticated: True 
    Authentication Type: Forms 
    Thread account name: xxxxxxxxxxx
 
Thread information: 
    Thread ID: 95 
    Thread account name: xxxxxxxxxxx 
    Is impersonating: False 
    Stack trace:    at System.Web.HttpResponse.set_ContentType(String value)
   at System.Web.Handlers.AssemblyResourceLoader.System.Web.IHttpHandler.ProcessRequest(HttpContext context)
 

TIA
andy

**Comment by araczynski** [comment]
Solved.  The issue was the default website that this was a part of had URL Rewrite rules that were interfering.  I created a separate site for this app and everything (and everyone) is happy.
